name: C Code Check (Windows)

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile C Code
        run: gcc *.c -o output.exe
